[package]
name = "bevy-x11-capture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.0"
x11cap = "0.4.1"

[patch.crates-io]
bevy = {path = "vendor/bevy"}
x11cap = {path = "vendor/X11Cap"}